syntax = "proto3";

package raiden_binary;

import "google/protobuf/timestamp.proto";

service RaidenBinaryService {
  rpc SubscribeBinaryTransactions(stream SubscribeBinaryTransactionsRequest) returns (stream SubscribeBinaryTransactionsResponse);
}

message SubscribeBinaryTransactionsRequest {
  map<string, SubscribeRequestFilterBinaryTransactions> transactions = 3;
}

message SubscribeBinaryTransactionsResponse {
  repeated string filters = 1;
  SubscribeUpdateBinaryTransaction transaction = 4;
  google.protobuf.Timestamp created_at = 11;
}

message SubscribeUpdateBinaryTransaction {
  BinaryTransaction transaction = 1;
  uint64 slot = 2;
  // ALT-resolved accounts. Empty for legacy transactions.
  repeated bytes loaded_writable_addresses = 3;
  repeated bytes loaded_readonly_addresses = 4;
}

message SubscribeRequestFilterBinaryTransactions {
  repeated string account_include = 3;
  repeated string account_exclude = 4;
  repeated string account_required = 6;
}

message BinaryTransaction {
  repeated bytes signatures = 1;
  // Serialized VersionedTransaction
  bytes binary_transaction = 3;
}
